spring:
  application:
    name: vc-products

server:
  port: ${PORT:0}

application:
  description: Rosario Central Products

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
