spring:
  application:
    name: vc-items

server:
  port: 8101

application:
  description: Rosario Central Items

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000